# Generated by Django 3.1.1 on 2020-09-16 03:08

from django.db import migrations

def create_data(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    Student(name="John Doe", email="Doe@gmail.com", document="22342342", phone="00000000", registrationDate="2020-09-13").save()

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
