# Generated by Django 3.1.1 on 2020-09-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registrationDate',
            field=models.DateField(auto_now_add=True, verbose_name='Registration Date'),
        ),
    ]
