# Generated by Django 3.1.1 on 2020-09-16 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students'),
        ('students', '0003_auto_20200916_0421'),
    ]

    operations = [
    ]
